#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 14 15:22:56 2021

@author: anish
"""

from itertools import combinations
from tabulate import tabulate
import sys
print('YOU CAN MAKE YOUR OWN NUMBER GUESSING GAME!!')
print('YOU NEED TO ENTER THE NUMBER UPTO WHICH YOU WANT THE PROGRAM TO MAKE THE GAME FOR YOU')
q=int(input('ENTER YOUR NUMBER '))
input("PRESS ENTER TO START THE GAME!!\n")
print('GUESSING GAME\n')
print('STEP1: THINK A NUMBER BETWEEN 1 AND',q)
input("Press Enter to continue...")
print('YOU WILL BE GETTING A NUMBER OF TABLES CONSISTING OF NUMBERS\n')
print('STEP 2: ENTER 1 FOR YES AND 0 FOR NO')


a=0
b=0
for i in range(1,100000):
  if i>0:
    r=0
    for j in range(0,i):
      comb = list(combinations([2**j for j in range(0,i)], j))
      #print(comb)
      r=r+len(comb)
      no=j  
  if r>q:
    #print(r)    
    #print(no)
    break

for i in range(1,no+2):
  globals()['b%s'%i]= [2**(i-1)]
  #print(globals()['b%s'%i])
for i in range(1,no+2):
  comb = list(combinations([2**j for j in range(0,no+1)], i))
  #print(comb)
  a=a+len(comb)
  #print(a)
  for j in comb:
    #print (j,sum(j))
    h= list(j)
    #print(h,sum(h))
    for k in h:
      for l in range(1,no+2):
        if k in globals()['b%s' % l]:
          globals()['b%s' % l].append(sum(h))

def newlist(x):
    while len(x)%(len(x)**0.5)!=0:
        x.append('~')
    tablise(x)
def tablise(x):
  trial_tab1=[]

  for i in range(0,len(x),int(len(x)**0.5)):
      trial_tab1.append(x[i:i+int((len(x)**0.5))])
 
  print(tabulate(trial_tab1,tablefmt="fancy_grid"))
def check(x):
  if (x!=1):
    if (x!=0):
      print('invalid input')
      sys.exit()

for i in range(1,no+2):
  #print(globals()['b%s'%i])
  l1= list(set(globals()['b%s'%i]))
  l2=[]
  for j in l1:
    if j<=q:
      l2.append(j)
  newlist(l2)
  globals()['guess%s' % i]= int(input('IS YOUR NUMBER HERE?'))
  check(globals()['guess%s' % i])
guess_dictionary={}
for i in range(0,no+1):  
   guess_dictionary["guess%s" %(i+1)] = 2**(i)
#print(guess_dictionary)
ans=0
for j in range(1,no+2):
  if globals()['guess%s'%j]==1:
    ans=ans+ guess_dictionary['guess%s'%j]
print('YOUR NUMBER IS',ans)
  


